// ═══════════════════════════════════════════════════════
// ISC2 CC Exam Question Bank — 200+ Tricky Scenario-Based Questions
// Answer stored as TEXT of correct option for shuffle-safe scoring
// ═══════════════════════════════════════════════════════

const questions = [

// ─────────────────────────────────────────────────────────
// DOMAIN 1: SECURITY PRINCIPLES (52 questions)
// ─────────────────────────────────────────────────────────

{domain:"Security Principles",question:"A company stores customer records in a database. Only authorized personnel should be able to read this data. Which component of the CIA Triad is PRIMARILY being protected?",options:["Availability","Integrity","Confidentiality","Non-repudiation"],answer:"Confidentiality",explanation:"Confidentiality ensures information is accessible only to authorized parties. Restricting read access is a confidentiality control."},

{domain:"Security Principles",question:"An employee receives an email appearing to be from the CEO, urgently requesting a wire transfer to an external account. This is BEST described as:",options:["A denial-of-service attack","A phishing/social engineering attack","A man-in-the-middle attack","A brute force attack"],answer:"A phishing/social engineering attack",explanation:"This is a Business Email Compromise (BEC) — a phishing attack using social engineering to impersonate authority and manipulate victims."},

{domain:"Security Principles",question:"A hospital's electronic health record system is modified by a disgruntled employee who changes patient medication dosages. Which CIA principle is MOST directly violated?",options:["Confidentiality","Integrity","Availability","Authentication"],answer:"Integrity",explanation:"Integrity ensures data is accurate and unaltered. Unauthorized modification of patient records directly violates data integrity."},

{domain:"Security Principles",question:"A hospital's patient portal goes offline during a ransomware attack. Which principle of the CIA Triad has been MOST directly violated?",options:["Confidentiality","Integrity","Availability","Authentication"],answer:"Availability",explanation:"Availability ensures systems are accessible when needed. Ransomware taking systems offline directly violates availability."},

{domain:"Security Principles",question:"A risk assessment reveals a vulnerability with HIGH likelihood of exploitation but LOW potential impact. What is the organization's BEST course of action?",options:["Immediately patch at any cost","Accept the risk without further action","Prioritize based on overall risk level and address accordingly","Ignore the vulnerability since impact is low"],answer:"Prioritize based on overall risk level and address accordingly",explanation:"Risk management balances likelihood and impact. High likelihood + low impact = moderate risk that should be prioritized proportionately."},

{domain:"Security Principles",question:"Which of the following BEST exemplifies the 'least privilege' principle?",options:["All employees have admin access for efficiency","A DBA can only access databases required for their specific job role","Users can request any access without formal approval","IT staff share a common admin account for simplicity"],answer:"A DBA can only access databases required for their specific job role",explanation:"Least privilege grants only the minimum permissions needed for job functions, reducing damage potential from errors or attacks."},

{domain:"Security Principles",question:"A company's security policy states: 'All employees must use MFA when accessing systems remotely.' This is an example of a:",options:["Standard","Guideline","Procedure","Policy"],answer:"Policy",explanation:"A policy is a high-level, mandatory directive from management. Standards specify the exact technology; procedures describe how."},

{domain:"Security Principles",question:"Which of the following BEST describes 'defense in depth'?",options:["Using a single, very strong security control","Deploying multiple layers of controls so if one fails, others remain","Training employees as the primary line of defense","Focusing all efforts on perimeter defenses"],answer:"Deploying multiple layers of controls so if one fails, others remain",explanation:"Defense in depth layers multiple controls (technical, administrative, physical) so bypassing one still leaves others protecting assets."},

{domain:"Security Principles",question:"An organization transfers data breach financial risk by purchasing cyber liability insurance. This risk treatment is called:",options:["Risk avoidance","Risk acceptance","Risk mitigation","Risk transference"],answer:"Risk transference",explanation:"Risk transference shifts financial consequences to a third party, such as through insurance or outsourcing."},

{domain:"Security Principles",question:"A system uses hashing to verify downloaded software hasn't been altered. Which CIA principle does this PRIMARILY support?",options:["Confidentiality","Availability","Integrity","Authentication"],answer:"Integrity",explanation:"Hashing verifies integrity. If the computed hash matches the published hash, the file hasn't been altered."},

{domain:"Security Principles",question:"An attacker intercepts and ALTERS communications between two parties without either knowing. This is BEST described as:",options:["Eavesdropping","A man-in-the-middle attack","A replay attack","A denial-of-service attack"],answer:"A man-in-the-middle attack",explanation:"A MitM attack secretly intercepts and potentially alters communications between two parties who believe they're communicating directly."},

{domain:"Security Principles",question:"The ISC2 Code of Ethics requires members to prioritize which of the following FIRST?",options:["The profession","Principals (employers and clients)","Society, the common good, and public trust","Individual professional development"],answer:"Society, the common good, and public trust",explanation:"ISC2 Code of Ethics canon priority: (1) Protect society, common good, public trust, and infrastructure — above employer and profession."},

{domain:"Security Principles",question:"An organization decides NOT to use a specific cloud service because the security risk is unacceptably high. This is:",options:["Risk mitigation","Risk acceptance","Risk avoidance","Risk transference"],answer:"Risk avoidance",explanation:"Risk avoidance eliminates risk entirely by not engaging in the activity that creates it."},

{domain:"Security Principles",question:"Separation of duties PRIMARILY prevents:",options:["System outages from single points of failure","Fraud by ensuring no single person controls a complete sensitive process","Unauthorized network access","Data loss from hardware failures"],answer:"Fraud by ensuring no single person controls a complete sensitive process",explanation:"Separation of duties divides critical tasks so no single person can commit and conceal wrongdoing."},

{domain:"Security Principles",question:"A CCTV camera system at building entrances is which type of control?",options:["Technical control","Administrative control","Physical control","Logical control"],answer:"Physical control",explanation:"Physical controls protect physical assets and environments. CCTV cameras deter, detect, and record unauthorized physical access."},

{domain:"Security Principles",question:"Which is the FIRST step in risk management?",options:["Implement controls","Identify assets and threats","Accept residual risk","Monitor existing controls"],answer:"Identify assets and threats",explanation:"Risk management starts with identifying assets, threats, and vulnerabilities. You can't assess or treat unidentified risks."},

{domain:"Security Principles",question:"A PIN combined with a fingerprint scan is an example of:",options:["Two-factor identification","Single-factor authentication","Multi-factor authentication","Biometric authorization"],answer:"Multi-factor authentication",explanation:"MFA requires two different factor types. PIN = 'something you know' + fingerprint = 'something you are' = two different factors."},

{domain:"Security Principles",question:"An attacker sends millions of login attempts to guess passwords. This is BEST described as:",options:["Phishing","SQL injection","Brute force attack","Replay attack"],answer:"Brute force attack",explanation:"Brute force systematically tries all possible password combinations until finding the correct one."},

{domain:"Security Principles",question:"Which term describes the potential for a threat to exploit a vulnerability and cause harm?",options:["Impact","Risk","Exposure","Threat agent"],answer:"Risk",explanation:"Risk is the potential for a threat to exploit a vulnerability, expressed as likelihood × impact."},

{domain:"Security Principles",question:"A vendor provides no security configuration guidance for their product. This lack of guidance is BEST described as a:",options:["Threat","Vulnerability","Risk","Control gap"],answer:"Vulnerability",explanation:"A vulnerability is a weakness in security. Lack of configuration guidance means systems may be deployed insecurely."},

{domain:"Security Principles",question:"Which describes 'privacy' in information security?",options:["Encrypting all data at rest","The right of individuals to control how their personal information is collected and used","Preventing all external access to networks","Storing data only on encrypted drives"],answer:"The right of individuals to control how their personal information is collected and used",explanation:"Privacy is the right and ability of individuals to control the collection, use, and disclosure of their personal data."},

{domain:"Security Principles",question:"Security awareness training is classified as which type of control?",options:["Technical control","Physical control","Administrative control","Compensating control"],answer:"Administrative control",explanation:"Administrative controls include policies, procedures, training, and guidelines. Security awareness training is management-based."},

{domain:"Security Principles",question:"What is the PRIMARY purpose of a security audit?",options:["Train employees on policies","Independently verify that controls are operating as intended","Install new security software","Respond to active incidents"],answer:"Independently verify that controls are operating as intended",explanation:"A security audit systematically examines whether security controls are implemented and functioning as intended."},

{domain:"Security Principles",question:"A policy states WHAT must be done. A procedure describes:",options:["WHY it must be done","HOW to implement the policy","WHO should approve the policy","WHEN the policy expires"],answer:"HOW to implement the policy",explanation:"Policies define high-level rules (the 'what'). Procedures provide step-by-step implementation instructions (the 'how')."},

{domain:"Security Principles",question:"Which authentication factor does a fingerprint scan represent?",options:["Something you know","Something you have","Something you are","Somewhere you are"],answer:"Something you are",explanation:"Biometrics (fingerprints, facial recognition, retina scans) are 'something you are' — inherence factors."},

{domain:"Security Principles",question:"A company encrypts all laptop hard drives to protect data if devices are stolen. This PRIMARILY protects:",options:["Availability","Integrity","Confidentiality","Non-repudiation"],answer:"Confidentiality",explanation:"Encryption at rest ensures stolen devices don't expose readable data — this is a confidentiality protection."},

// ─── NEW TRICKY Domain 1 questions ───

{domain:"Security Principles",question:"A security team discovers that a critical server patch breaks a legacy business application. The security manager insists on patching; the business unit demands the application stay running. What is the BEST approach?",options:["Patch immediately regardless of business impact","Leave the system unpatched to maintain business operations","Perform a risk assessment to weigh vulnerability severity against business impact, and implement compensating controls if patching is delayed","Escalate to law enforcement"],answer:"Perform a risk assessment to weigh vulnerability severity against business impact, and implement compensating controls if patching is delayed",explanation:"ISC2 emphasizes security as a business function. The best approach balances security risk with business needs through formal risk assessment and compensating controls."},

{domain:"Security Principles",question:"An organization implements a new password policy requiring 16-character passwords changed every 90 days. Employees begin writing passwords on sticky notes. The MOST likely root cause is:",options:["Employees are not trained on cybersecurity","The policy prioritizes security without considering usability","The organization lacks a security culture","The password policy is too lenient"],answer:"The policy prioritizes security without considering usability",explanation:"Security controls must be usable. Overly complex requirements lead to workarounds that undermine security. The policy failed to balance security with human factors."},

{domain:"Security Principles",question:"During a security incident investigation, an analyst discovers the attacker exploited a vulnerability that was identified in a risk assessment six months ago but classified as 'accepted risk.' Who is ultimately responsible for this accepted risk?",options:["The security analyst who identified the vulnerability","The IT administrator who manages the system","Senior management who accepted the risk","The attacker who exploited the vulnerability"],answer:"Senior management who accepted the risk",explanation:"Risk acceptance is a management decision. Senior management is ultimately accountable for risk decisions and their consequences."},

{domain:"Security Principles",question:"An organization wants to ensure that digital contracts cannot be later denied by the signing party. Which security concept BEST addresses this requirement?",options:["Confidentiality","Integrity","Non-repudiation","Authentication"],answer:"Non-repudiation",explanation:"Non-repudiation ensures a party cannot deny having performed an action, such as signing a contract. Digital signatures provide non-repudiation."},

{domain:"Security Principles",question:"A company's disaster recovery site has all necessary hardware but requires data restoration from backups and takes 24-48 hours to become operational. This site is BEST classified as a:",options:["Hot site","Warm site","Cold site","Mirror site"],answer:"Warm site",explanation:"A warm site has pre-installed hardware but needs data restoration. Hot sites are immediately operational; cold sites have only basic infrastructure."},

{domain:"Security Principles",question:"Three employees each hold one of three separate keys required to open a vault containing classified documents. This is an example of:",options:["Separation of duties","Dual control","Split knowledge","Least privilege"],answer:"Split knowledge",explanation:"Split knowledge divides a secret into multiple parts held by different people. No single person possesses the complete secret needed for access."},

{domain:"Security Principles",question:"An organization detects that a former employee's account was used to access sensitive files two weeks after their termination. The MOST likely process failure is:",options:["Lack of encryption on sensitive files","Failure to implement access reviews during offboarding","Insufficient network monitoring","Weak password policy"],answer:"Failure to implement access reviews during offboarding",explanation:"The core failure is in the offboarding process — access should be revoked immediately upon termination. This is an administrative control failure."},

{domain:"Security Principles",question:"A software developer has read access to production databases for debugging. They request write access to 'fix issues faster.' Applying the principle of least privilege, the BEST response is:",options:["Grant write access since they already have read access","Grant temporary, monitored write access only for specific approved incidents","Deny all access to production databases","Grant write access but log all changes"],answer:"Grant temporary, monitored write access only for specific approved incidents",explanation:"Least privilege means granting only what's needed, when it's needed. Temporary, scoped, and monitored access balances operational needs with security."},

{domain:"Security Principles",question:"Which type of security control is an 'employee background check' performed before hiring?",options:["Detective control","Preventive control","Corrective control","Recovery control"],answer:"Preventive control",explanation:"Background checks prevent potentially untrustworthy individuals from gaining access to an organization's assets — they act before harm occurs."},

{domain:"Security Principles",question:"An organization outsources its email security to a cloud provider. If a data breach occurs through the cloud email system, who bears PRIMARY responsibility for protecting customer data?",options:["The cloud provider exclusively","The organization that owns the data","Both equally with no distinction","The customers whose data was breached"],answer:"The organization that owns the data",explanation:"Data ownership means the organization remains ultimately responsible for data protection, regardless of where processing occurs. You can outsource functions but not responsibility."},

{domain:"Security Principles",question:"A firewall, an IDS, encryption, and security awareness training are used together to protect a web application. This approach is BEST described as:",options:["Risk avoidance","Defense in depth","Security through obscurity","Compensating controls"],answer:"Defense in depth",explanation:"Defense in depth layers multiple types of controls (technical, administrative) so that failure of one control doesn't compromise the system."},

{domain:"Security Principles",question:"An organization's risk register shows: Threat A (likelihood: High, impact: Low), Threat B (likelihood: Low, impact: High), Threat C (likelihood: Medium, impact: Medium). With limited budget, which should be addressed FIRST?",options:["Threat A — high likelihood means it will likely occur","Threat B — high impact could be catastrophic","Threat C — balanced risk profile suggests immediate attention","All threats should be addressed simultaneously regardless of budget"],answer:"Threat B — high impact could be catastrophic",explanation:"While all risks need attention, high-impact threats should generally be prioritized because their consequences could be catastrophic even if less frequent."},

{domain:"Security Principles",question:"A security policy states: 'USB drives are prohibited on all workstations.' A department manager requests an exception for transferring large design files. The BEST approach is:",options:["Deny the request — policy is policy","Grant the exception without documentation since the manager has authority","Follow the formal exception process: document the business justification, implement compensating controls, obtain senior management approval","Allow USB drives for the entire department"],answer:"Follow the formal exception process: document the business justification, implement compensating controls, obtain senior management approval",explanation:"Security policies should have formal exception processes. Exceptions need business justification, compensating controls, and management approval."},

{domain:"Security Principles",question:"During a penetration test, the tester discovers they can access the CEO's email without authorization. The FIRST action should be to:",options:["Read the emails to assess the full scope of the vulnerability","Immediately report the finding to the designated point of contact","Attempt to access other executive accounts to test breadth","Post the finding to a public vulnerability database"],answer:"Immediately report the finding to the designated point of contact",explanation:"Ethical conduct requires immediately reporting critical findings through proper channels. Reading emails exceeds the scope and violates ethics."},

{domain:"Security Principles",question:"Which concept BEST describes ensuring that audit logs cannot be modified after they are written?",options:["Confidentiality of logs","Integrity of logs","Availability of logs","Non-repudiation of logs"],answer:"Integrity of logs",explanation:"Ensuring logs cannot be modified after writing protects their integrity — they remain accurate, complete, and trustworthy for forensic purposes."},

{domain:"Security Principles",question:"An employee uses their personal email to send work documents home for 'convenience.' Even without malicious intent, this PRIMARILY creates a risk to:",options:["Availability — the documents might become unavailable","Integrity — the documents might be altered","Confidentiality — the documents leave the organization's security controls","Non-repudiation — the employee can deny sending the documents"],answer:"Confidentiality — the documents leave the organization's security controls",explanation:"Sending work documents through personal email bypasses organizational security controls, exposing confidential data to uncontrolled environments."},

// ─────────────────────────────────────────────────────────
// DOMAIN 2: BUSINESS CONTINUITY, DR & IR (22 questions)
// ─────────────────────────────────────────────────────────

{domain:"Business Continuity, DR & IR",question:"What is the PRIMARY purpose of a Business Continuity Plan (BCP)?",options:["Identify the cause of an outage after it occurs","Ensure critical business functions can continue during and after a disruption","Recover all IT systems within 24 hours","Document all hardware and software assets"],answer:"Ensure critical business functions can continue during and after a disruption",explanation:"A BCP ensures critical business functions continue during and after disruption — it's about business operations, not just IT recovery."},

{domain:"Business Continuity, DR & IR",question:"Which term describes the maximum acceptable time to restore a system after a disaster?",options:["Recovery Point Objective (RPO)","Recovery Time Objective (RTO)","Maximum Tolerable Downtime (MTD)","Mean Time to Recover (MTTR)"],answer:"Recovery Time Objective (RTO)",explanation:"RTO is the maximum acceptable time to restore a system. It defines how long the business can tolerate the outage."},

{domain:"Business Continuity, DR & IR",question:"A company performs data backups every 24 hours. If disaster strikes, the maximum data loss is described by which metric?",options:["Recovery Time Objective (RTO)","Maximum Tolerable Downtime (MTD)","Recovery Point Objective (RPO)","Service Level Agreement (SLA)"],answer:"Recovery Point Objective (RPO)",explanation:"RPO is maximum acceptable data loss measured in time. With 24-hour backups, up to 24 hours of data could be lost."},

{domain:"Business Continuity, DR & IR",question:"During incident response, which phase involves identifying lessons learned and updating procedures?",options:["Detection","Containment","Eradication","Post-incident activity"],answer:"Post-incident activity",explanation:"Post-incident activity (lessons learned) reviews the incident, documents findings, and updates procedures to prevent recurrence."},

{domain:"Business Continuity, DR & IR",question:"Unusual outbound network traffic is detected from a workstation. What should happen FIRST?",options:["Eradicate the malware immediately","Contain the affected system to prevent further damage","Notify law enforcement","Restore from backup"],answer:"Contain the affected system to prevent further damage",explanation:"Containment follows detection. Isolating the system prevents spread while preserving evidence for investigation."},

{domain:"Business Continuity, DR & IR",question:"A fully equipped alternate data center that can take over operations almost immediately is called a:",options:["Cold site","Warm site","Hot site","Mobile site"],answer:"Hot site",explanation:"A hot site is fully operational with current data and can take over almost immediately — shortest RTO of all recovery sites."},

{domain:"Business Continuity, DR & IR",question:"A Business Impact Analysis (BIA) is PRIMARILY used to:",options:["Train employees on incident response","Identify critical business functions and the impact of disruptions","Test existing security controls","Develop security policy"],answer:"Identify critical business functions and the impact of disruptions",explanation:"A BIA identifies and prioritizes critical functions, quantifies disruption impact, and determines RTO/RPO requirements."},

{domain:"Business Continuity, DR & IR",question:"BC focuses on keeping the business running; DR focuses on:",options:["Keeping the business running — they're identical","Restoring IT systems after a disruption","Preventing disruptions from occurring","Training employees on emergency procedures"],answer:"Restoring IT systems after a disruption",explanation:"BC maintains business operations during disruption. DR is a subset focused specifically on recovering IT infrastructure after disaster."},

{domain:"Business Continuity, DR & IR",question:"Which incident response step involves removing malware and closing exploited vulnerabilities?",options:["Identification","Containment","Eradication","Recovery"],answer:"Eradication",explanation:"Eradication removes the root cause — deleting malware, closing vulnerabilities, disabling compromised accounts."},

{domain:"Business Continuity, DR & IR",question:"A company activates a pre-arranged contract to use another company's data center temporarily after a fire. This is a:",options:["Hot site","Cold site","Warm site","Reciprocal agreement"],answer:"Reciprocal agreement",explanation:"A reciprocal agreement is a mutual arrangement between organizations to provide backup facilities to each other during disasters."},

// ─── NEW TRICKY Domain 2 questions ───

{domain:"Business Continuity, DR & IR",question:"An organization's RTO for its e-commerce platform is 4 hours, but its current backup restoration process takes 8 hours. What is the BEST course of action?",options:["Accept the gap and inform stakeholders of the extended recovery time","Change the RTO to 8 hours to match current capabilities","Invest in faster recovery solutions to meet the 4-hour RTO","Eliminate the e-commerce platform to avoid the risk entirely"],answer:"Invest in faster recovery solutions to meet the 4-hour RTO",explanation:"RTO is determined by business needs. If current capabilities don't meet it, the organization must invest in solutions that do, or face unacceptable business impact."},

{domain:"Business Continuity, DR & IR",question:"During an incident, the team identifies that the attacker is still actively exfiltrating data. What takes HIGHEST priority?",options:["Begin forensic analysis to determine the attack vector","Contain the breach to stop ongoing data exfiltration","Notify regulatory authorities of the breach","Prepare a press release for public disclosure"],answer:"Contain the breach to stop ongoing data exfiltration",explanation:"When an attack is actively ongoing, containment to stop the bleeding takes highest priority. Investigation and notification follow after the active threat is controlled."},

{domain:"Business Continuity, DR & IR",question:"A tabletop exercise is BEST described as:",options:["A full simulation where systems are actually shut down to test recovery","A discussion-based walkthrough of a simulated scenario without executing actual response actions","A technical test of backup restoration procedures","An unannounced drill that tests employee reaction time"],answer:"A discussion-based walkthrough of a simulated scenario without executing actual response actions",explanation:"Tabletop exercises are discussion-based — participants talk through a scenario to identify gaps without affecting production systems."},

{domain:"Business Continuity, DR & IR",question:"After a ransomware attack, the IT team restores systems from clean backups. Before returning systems to production, the MOST important step is:",options:["Pay the ransom to ensure decryption keys are available as backup","Verify that the vulnerability exploited by the ransomware has been patched","Immediately restore all systems simultaneously to minimize downtime","Notify the media about the successful recovery"],answer:"Verify that the vulnerability exploited by the ransomware has been patched",explanation:"Before returning to production, you must ensure the vulnerability is patched — otherwise the same attack can simply recur."},

{domain:"Business Continuity, DR & IR",question:"An organization has never tested its disaster recovery plan. During a real disaster, the plan fails. The PRIMARY lesson learned is:",options:["Disaster recovery plans are unnecessary","Plans must be regularly tested and updated to ensure they work when needed","The organization should outsource all disaster recovery","Technology solutions are more important than documented plans"],answer:"Plans must be regularly tested and updated to ensure they work when needed",explanation:"Untested plans are unreliable. Regular testing (tabletop, simulation, full tests) identifies gaps before real disasters expose them."},

{domain:"Business Continuity, DR & IR",question:"A company's BIA identifies that the finance department's payment processing system has an MTD of 2 hours. This means:",options:["The system must be backed up every 2 hours","The system can tolerate a maximum of 2 hours of downtime before unacceptable business impact occurs","The system must be patched within 2 hours of a vulnerability being discovered","The system must be audited every 2 hours"],answer:"The system can tolerate a maximum of 2 hours of downtime before unacceptable business impact occurs",explanation:"Maximum Tolerable Downtime (MTD) is the total time a business can survive without a system before suffering unacceptable consequences."},

{domain:"Business Continuity, DR & IR",question:"During incident response, preserving evidence for potential legal proceedings is MOST important during which phase?",options:["Preparation","Containment","Eradication","Recovery"],answer:"Containment",explanation:"During containment, it's critical to preserve evidence (forensic images, logs) while stopping the incident. Hasty eradication can destroy evidence."},

{domain:"Business Continuity, DR & IR",question:"An organization's incident response plan assigns the role of 'incident commander.' This person's PRIMARY responsibility is to:",options:["Personally fix all technical issues","Coordinate the overall response effort and make critical decisions","Write the post-incident report","Contact the media"],answer:"Coordinate the overall response effort and make critical decisions",explanation:"The incident commander leads and coordinates the response team, makes critical decisions, and ensures proper communication — they don't fix everything personally."},

{domain:"Business Continuity, DR & IR",question:"Which of the following is NOT typically a phase of incident response?",options:["Preparation","Risk transfer","Containment","Lessons learned"],answer:"Risk transfer",explanation:"The standard IR phases are: Preparation, Detection/Identification, Containment, Eradication, Recovery, and Lessons Learned. Risk transfer is a risk management strategy, not an IR phase."},

{domain:"Business Continuity, DR & IR",question:"A company's backup strategy uses full backups on Sunday and incremental backups Monday through Saturday. A failure occurs on Wednesday. To restore, you need:",options:["Only Wednesday's incremental backup","Sunday's full backup only","Sunday's full backup plus Monday, Tuesday, and Wednesday incremental backups","All seven days of backups"],answer:"Sunday's full backup plus Monday, Tuesday, and Wednesday incremental backups",explanation:"Incremental backups capture only changes since the last backup. Full restoration requires the last full backup plus all subsequent incrementals."},

{domain:"Business Continuity, DR & IR",question:"A cold site provides:",options:["Fully operational systems with real-time data replication","Pre-installed hardware requiring only data restoration","Basic infrastructure (power, connectivity) but no pre-installed hardware or data","A mobile trailer with complete computing capabilities"],answer:"Basic infrastructure (power, connectivity) but no pre-installed hardware or data",explanation:"A cold site has only basic facilities. Hardware must be procured and installed, data restored. It's cheapest but has the longest recovery time."},

{domain:"Business Continuity, DR & IR",question:"After an incident, the team discovers that critical security logs were overwritten due to insufficient storage. This gap should be addressed in which IR phase?",options:["Detection","Containment","Recovery","Lessons learned"],answer:"Lessons learned",explanation:"The lessons learned phase identifies gaps (like insufficient log storage) and implements improvements to prevent the same problems in future incidents."},
];
